# Generated by Django 4.0.6 on 2022-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0002_delete_movies_movie_genre_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
