# Generated by Django 4.0.6 on 2022-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0003_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
