# Generated by Django 4.0.6 on 2022-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0004_alter_movie_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie-posters/'),
        ),
    ]
